apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      nodePort: 30005
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      tier: ci-cd
  template:
    metadata:
      labels:
        app: jenkins
        tier: ci-cd
    spec:
      containers:
      - name: jenkins
        image: eamquindio/jenkinsseminario:v1.0 
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-volume
      volumes:
      - name: jenkins-volume
        hostPath:
          # directory location on host
          path: /Users/caferrerb/eam/volume/jenkins
          # this field is optional
          type: Directory